[technote]
id = "RTN-103"
series_id = "RTN"
canonical_url = "https://rtn-103.lsst.io"
github_url = "https://github.com/lsst/rtn-103"
github_default_branch = "main"
date_created = 2025-06-30T13:55:25Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Quentin"
name.family = "Le Boulc'h"
internal_id = "leboulchq"

[[technote.authors.affiliations]]
name = "CNRS"
internal_id = "Lyon-CC-IN2P3"
address = "CC-IN2P3, 21 avenue Pierre de Coubertin, CS70202, F-69627 Villeurbanne cedex, France"
